export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY'

export const FETCH_ROBOTS_SUCCESS = 'FETCH_ROBOTS_SUCCESS'
export const FETCH_ROBOTS_FAILED = 'FETCH_ROBOTS_FAILED'
export const FETCH_ROBOTS_PENDING = 'FETCH_ROBOTS_PENDING'
